### ISSUE TITLE
[Question] How does this relate with rufo?

### ISSUE THREAD

**Issue by acnovais** [iamsolankiamit/prettier-ruby#1]
Hi there,
This is pretty cool stuff. 
I am considering applying a more opinionated formatter (aka no rubocop) on a ruby codebase and by being a user of prettier on JS land I came across this plugin. But I also came across with https://github.com/ruby-formatter/rufo.
Could you give me some insight on the direction of this project and why using prettier with a ruby plugin would be a better approach?
I'm thinking that it may be a bit strange to manage different language package managers on ruby project or are you thinking on a different approach?

Thanks!

**Comment by iamsolankiamit** [comment]
Hey @acnovais, Rufo is cool. I didn't know about it before, but after checking it out, I still feel that I should go ahead with prettier-ruby.
What I don't like about Rufo is that it allows custom indentation for each user, as in I can format my arrays into a multi-line array, and Rufo will be fine with it, even if it fits properly in one line and multi-line was unnecessary. This way the repo will have different formatting based each users preferences.
What I like about Rufo is that it is completely in Ruby, which can be useful where having multiple language dependencies is not possible.

As for Prettier-Ruby, the Idea is to get a working version out fast, and then iterate over things which come secondary, like:
* Having custom Ast-processor, to remove dependencies on multiple gems, and to generate JSON directly when parsing rather than after.
* Improving support for multiple versions.
* Possibly move from JS to Ruby completely (If a lot of people want that).

Let me know if you have any more questions, Ideas, etc.

**Comment by acnovais** [comment]
Awesome, thanks for you insights! 🙏
